
AGE_START_DICT_KEY = 'age-start'
AGE_STOP_DICT_KEY = 'age-stop'
FEMALE_QUANTITY = 'female-quantity'
MALE_QUANTITY = 'male-quantity'

MAX_ORDER_NUMBER = 9999
MALE_SEX_NUMBER_SET = (1, 3, 5, 7, 9)
FEMALE_SEX_NUMBER_SET = (0, 2, 4, 6, 8)

DAILY_LIMIT = 50000
